[openai]
api_key = "tgp_v1_fIrEkVv7FFTdfdvSTdw6d-4DnSEPUfpyWhFYtQYtV9k"
[mongo]
uri = "mongodb+srv://Hitesh-admin:0NJSMORTSg6Fmj4e@cluster0.dzr401v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"